name: Language Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: StefVuck/Github-Language-Stats@v1
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "donut"
          dark_mode: "true"
          exclude_languages: "HTML,CSS"
          output_path: "github-stats"
          include_forks: "false"
          commit_message: "Update language statistics"
